import pygame

FRAME_RATE = 30
MAX_PLAYER_VELOCITY = 2.83
MAX_PUCK_VELOCITY = MAX_PLAYER_VELOCITY * 5
FRICTION = 0.01
SHOT_VELOCITY = 20
PASS_VELOCITY = 5
ELASTICITY = 1
RINK_SCALE = 5
BOARD_THICKNESS = 5
RINK_WIDTH = 200 * RINK_SCALE
RINK_HEIGHT = 85 * RINK_SCALE
SCREEN_WIDTH = RINK_WIDTH + 2 * BOARD_THICKNESS
SCREEN_HEIGHT = RINK_HEIGHT + 2 * BOARD_THICKNESS
NET_WIDTH = 4 * RINK_SCALE
NET_HEIGHT = 6 * RINK_SCALE
PUCK_WIDTH = 2 * RINK_SCALE
PUCK_HEIGHT = 2 * RINK_SCALE
PLAYER_WIDTH = 3 * RINK_SCALE
PLAYER_HEIGHT = 3 * RINK_SCALE
GOAL_BOX_HEIGHT = 4 * RINK_SCALE
GOAL_BOX_WIDTH = 1 * RINK_SCALE
LEFT_GOAL_EVENT = pygame.USEREVENT + 1
RIGHT_GOAL_EVENT = pygame.USEREVENT + 2